### ISSUE TITLE
Transform operator for open lineage throw exception

### ISSUE THREAD

**Issue by pankajastro** [astronomer/astro-sdk#1112]
**Describe the bug**
DAG
```
from airflow import DAG
from datetime import datetime

from astro.table import Table
from astro import sql as aql

with DAG(dag_id="test", schedule_interval=None, start_date=datetime(1970, 1, 1), catchup=False) as dag:
    @aql.transform
    def select(input_table: Table):
        return "SELECT * FROM {{ input_table }} LIMIT 4;"  # {{ input_table }} was also failing
    select(
        input_table=Table(metadata={"schema": "Benchmark"}, name="load_files_to_database", conn_id="google_cloud_default"),
        output_table=Table(metadata={"schema": "Benchmark"}, conn_id="google_cloud_default")
    )
```

Task Log
```
d20917c78224
*** Reading local file: /usr/local/airflow/logs/dag_id=test/run_id=manual__2022-10-20T09:57:46.691662+00:00/task_id=select/attempt=1.log
[2022-10-20, 09:57:50 UTC] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: test.select manual__2022-10-20T09:57:46.691662+00:00 [queued]>
[2022-10-20, 09:57:50 UTC] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: test.select manual__2022-10-20T09:57:46.691662+00:00 [queued]>
[2022-10-20, 09:57:50 UTC] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-20, 09:57:50 UTC] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-10-20, 09:57:50 UTC] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-20, 09:57:50 UTC] {listener.py:27} INFO - TaskInstance Details: dag_id=test, task_id=select, dagrun_id=manual__2022-10-20T09:57:46.691662+00:00, map_index=-1, run_start_date=2022-10-20 09:57:50.277838+00:00, try_number=1, job_id=172, op_classpath=astro.sql.operators.transform.TransformOperator
[2022-10-20, 09:57:50 UTC] {adapter.py:68} ERROR - Failed to emit OpenLineage event of id ab6b126e-ee85-48c4-8a91-0e3e8584a5ae
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x403462ff40>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=5050): Max retries exceeded with url: /api/v1/lineage (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x403462ff40>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/openlineage/airflow/adapter.py", line 66, in emit
    return self.get_or_create_openlineage_client().emit(event)
  File "/usr/local/lib/python3.9/site-packages/openlineage/client/client.py", line 69, in emit
    self.transport.emit(event)
  File "/usr/local/lib/python3.9/site-packages/openlineage/client/transport/http.py", line 122, in emit
    resp = self.session.post(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='host.docker.internal', port=5050): Max retries exceeded with url: /api/v1/lineage (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x403462ff40>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2022-10-20, 09:57:50 UTC] {taskinstance.py:1383} INFO - Executing <Task(TransformOperator): select> on 2022-10-20 09:57:46.691662+00:00
[2022-10-20, 09:57:50 UTC] {standard_task_runner.py:55} INFO - Started process 1880 to run task
[2022-10-20, 09:57:50 UTC] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'test', 'select', 'manual__2022-10-20T09:57:46.691662+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/transform_op.py', '--cfg-path', '/tmp/tmpz91zklyn']
[2022-10-20, 09:57:50 UTC] {standard_task_runner.py:83} INFO - Job 172: Subtask select
[2022-10-20, 09:57:51 UTC] {task_command.py:376} INFO - Running <TaskInstance: test.select manual__2022-10-20T09:57:46.691662+00:00 [running]> on host d20917c78224
[2022-10-20, 09:57:51 UTC] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=select
AIRFLOW_CTX_EXECUTION_DATE=2022-10-20T09:57:46.691662+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-20T09:57:46.691662+00:00
[2022-10-20, 09:57:51 UTC] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-10-20, 09:57:53 UTC] {base_decorator.py:123} INFO - Returning table TempTable(_name='', conn_id='google_cloud_default', metadata=Metadata(schema='Benchmark', database=None), columns=[], temp=True)
[2022-10-20, 09:57:53 UTC] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-10-20, 09:57:53 UTC] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-10-20, 09:57:53 UTC] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-10-20, 09:57:54 UTC] {bigquery.py:1053} INFO - Dataset Resource: Dataset(DatasetReference('astronomer-dag-authoring', 'Benchmark'))
[2022-10-20, 09:57:55 UTC] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-10-20, 09:57:55 UTC] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-10-20, 09:57:57 UTC] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-10-20, 09:57:57 UTC] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-10-20, 09:58:01 UTC] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=test, task_id=select, execution_date=20221020T095746, start_date=20221020T095750, end_date=20221020T095801
[2022-10-20, 09:58:01 UTC] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-10-20, 09:58:01 UTC] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-10-20, 09:58:01 UTC] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-10-20, 09:58:01 UTC] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-10-20, 09:58:01 UTC] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-10-20, 09:58:01 UTC] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-10-20, 09:58:01 UTC] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-10-20, 09:58:01 UTC] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-10-20, 09:58:01 UTC] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-10-20, 09:58:03 UTC] {manager.py:63} ERROR - Failed to extract metadata _tmp_lyjsgatlhmm99ajrl2ogkp04aatymak0ih0ecr9vichhhjz3 task_type=TransformOperator ***_dag_id=test task_id=select ***_run_id=manual__2022-10-20T09:57:46.691662+00:00 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy_bigquery/base.py", line 937, in _get_table
    table = client.get_table(table_ref)
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 1034, in get_table
    api_response = self._call_api(
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/usr/local/lib/python3.9/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 GET https://bigquery.googleapis.com/bigquery/v2/projects/astronomer-dag-authoring/datasets/Benchmark/tables/_tmp_lyjsgatlhmm99ajrl2ogkp04aatymak0ih0ecr9vichhhjz3?prettyPrint=false: Not found: Table astronomer-dag-authoring:Benchmark._tmp_lyjsgatlhmm99ajrl2ogkp04aatymak0ih0ecr9vichhhjz3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/openlineage/airflow/extractors/manager.py", line 46, in extract_metadata
    task_metadata = extractor.extract_on_complete(task_instance)
  File "/usr/local/airflow/astro_sdk/src/astro/lineage/extractor.py", line 53, in extract_on_complete
    open_lineage_facets: OpenLineageFacets = self.operator.get_openlineage_facets(task_instance)
  File "/usr/local/airflow/astro_sdk/src/astro/sql/operators/base_decorator.py", line 219, in get_openlineage_facets
    "stats": OutputStatisticsOutputDatasetFacet(rowCount=self.output_table.row_count)
  File "/usr/local/airflow/astro_sdk/src/astro/table.py", line 135, in row_count
    tb = db.get_sqla_table(table=self)
  File "/usr/local/airflow/astro_sdk/src/astro/databases/base.py", line 609, in get_sqla_table
    return SqlaTable(
  File "<string>", line 2, in __new__
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 607, in __new__
    metadata._remove_table(name, schema)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 602, in __new__
    table._init(name, metadata, *args, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 677, in _init
    self._autoload(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 712, in _autoload
    conn_insp.reflect_table(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 774, in reflect_table
    for col_d in self.get_columns(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 497, in get_columns
    col_defs = self.dialect.get_columns(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy_bigquery/base.py", line 950, in get_columns
    table = self._get_table(connection, table_name, schema)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy_bigquery/base.py", line 939, in _get_table
    raise NoSuchTableError(table_name)
sqlalchemy.exc.NoSuchTableError: _tmp_lyjsgatlhmm99ajrl2ogkp04aatymak0ih0ecr9vichhhjz3
[2022-10-20, 09:58:03 UTC] {adapter.py:68} ERROR - Failed to emit OpenLineage event of id ab6b126e-ee85-48c4-8a91-0e3e8584a5ae
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x4046fe6910>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=5050): Max retries exceeded with url: /api/v1/lineage (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x4046fe6910>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/openlineage/airflow/adapter.py", line 66, in emit
    return self.get_or_create_openlineage_client().emit(event)
  File "/usr/local/lib/python3.9/site-packages/openlineage/client/client.py", line 69, in emit
    self.transport.emit(event)
  File "/usr/local/lib/python3.9/site-packages/openlineage/client/transport/http.py", line 122, in emit
    resp = self.session.post(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='host.docker.internal', port=5050): Max retries exceeded with url: /api/v1/lineage (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x4046fe6910>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2022-10-20, 09:58:03 UTC] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-10-20, 09:58:03 UTC] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check


```

**To Reproduce**
- Create GCP connection `google_cloud_default`
- Run the above DAG
- You see the above exception

**Expected behavior**
It should not throw an exception

**Screenshots**

**Additional context**

**Comment by pankajastro** [comment]
Look like lineage server was not running. unable to reproduce.
