### ISSUE TITLE
TypeError: list indices must be integers or slices, not str when running example dag [BUG]

### ISSUE THREAD

**Issue by kelechi2020** [astronomer/astro-sdk#1335]
**Describe the bug**

I get this error also when running the [dag](https://github.com/astronomer/astro-sdk/blob/main/python-sdk/example_dags/example_amazon_s3_snowflake_transform.py)
Details: 
[2022-11-30, 21:35:07 UTC] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=example_amazon_s3_snowflake_transform, task_id=load_file, execution_date=20221130T213456, start_date=20221130T213459, end_date=20221130T213507

Airflow version: 2.4.3+astro.1
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/astro/sql/operators/load_file.py", line 81, in execute
    return self.load_data(input_file=self.input_file)
  File "/usr/local/lib/python3.9/site-packages/astro/sql/operators/load_file.py", line 87, in load_data
    return self.load_data_to_table(input_file)
  File "/usr/local/lib/python3.9/site-packages/astro/sql/operators/load_file.py", line 104, in load_data_to_table
    database.load_file_to_table(
  File "/usr/local/lib/python3.9/site-packages/astro/databases/base.py", line 418, in load_file_to_table
    self.create_schema_and_table_if_needed(
  File "/usr/local/lib/python3.9/site-packages/astro/databases/base.py", line 373, in create_schema_and_table_if_needed
    self.create_schema_if_needed(table.metadata.schema)
  File "/usr/local/lib/python3.9/site-packages/astro/databases/base.py", line 686, in create_schema_if_needed
    if schema and not self.schema_exists(schema):
  File "/usr/local/lib/python3.9/site-packages/astro/databases/snowflake.py", line 733, in schema_exists
    created_schemas = [x["SCHEMA_NAME"] for x in schemas]
  File "/usr/local/lib/python3.9/site-packages/astro/databases/snowflake.py", line 733, in <listcomp>
    created_schemas = [x["SCHEMA_NAME"] for x in schemas]
TypeError: list indices must be integers or slices, not str
```
**Version**
* Astro-sdk: [e.g. 1.2.3]

**To Reproduce**
1. Run the  the [DAG](https://github.com/astronomer/astro-sdk/blob/main/python-sdk/example_dags/example_amazon_s3_snowflake_transform.py)  '...'
2. Create connection '....'

**Comment by phanikumv** [comment]
This issue is fixed in https://github.com/astronomer/astro-sdk/pull/1324/
