### ISSUE TITLE
In-memory DuckDB should load upstream dataframes

### ISSUE THREAD

**Issue by pgzmnk** [astronomer/astro-sdk#1831]
**Describe the bug**

Cloud IDE will enable a feature where `@aql.run_raw_sql` cells without a specified connection will default to using `duckdb_default`. That connection is `duckdb://` and should result in `duckdb:///:memory:` being set, and duckdb running the task in-memory.

Currently, a duckdb Task configured as above is unable to load a referenced upstream dataframe ([sample Astro CLI repo](https://github.com/astronomer/duckdb-demo/blob/main/dags/duckdb.py)). 

To address this, the SDK should be configured to load the data and execute the task without closing the duckdb in-memory session in between.

This is time sensitive as the IDE feature described above depends on it.

**Version**
* Astro: 1.5.2

**To Reproduce**
[sample Astro CLI repo](https://github.com/astronomer/duckdb-demo/blob/main/dags/duckdb.py)

**Expected behavior**

`@aql.run_raw_sql` Task with in-memory duckdb connection successfully loads referenced dataframe from upstream Task.

**Screenshots**

![image](https://user-images.githubusercontent.com/27398253/223167588-f1c60dbc-71d8-4cdd-b4c2-07a463208b30.png)
_Figure 1: Cloud IDE pipeline where Postgres cell successfully loads upstream dataframe, but in-memory duckdb cell does not._

**Additional context**

- [Screenshots in related issue.](https://github.com/astronomer/astro/issues/10009#issuecomment-1451014067)
- [Slack thread discussing solution.](https://astronomer.slack.com/archives/C03868KGF2Q/p1677776130530249?thread_ts=1677776123.892059&cid=C03868KGF2Q)

**Comment by pgzmnk** [comment]
Related logs

```
2023-03-01T23:26:53.607Z] File "/run/clehe8kvc0008ednwcxhe1xge/sqlalchemy/engine/base.py", line 1900, in _execute_context
[2023-03-01T23:26:53.607Z] self.dialect.do_execute(
[2023-03-01T23:26:53.607Z] File "/run/clehe8kvc0008ednwcxhe1xge/sqlalchemy/engine/default.py", line 736, in do_execute
[2023-03-01T23:26:53.607Z] cursor.execute(statement, parameters)
[2023-03-01T23:26:53.607Z] File "/run/clehe8kvc0008ednwcxhe1xge/duckdb_engine/__init__.py", line 128, in execute
[2023-03-01T23:26:53.607Z] self.__c.execute(statement, parameters)
[2023-03-01T23:26:53.607Z] duckdb.CatalogException: Catalog Error: Table with name ivsubvehnah8o06y6hh0qxlzgnaompd78kfj9e3216lgoyxzldiy02h7we3qi4 does not exist!
[2023-03-01T23:26:53.607Z] Did you mean "pragma_database_list"?
[2023-03-01T23:26:53.607Z] LINE 2: SELECT * FROM ivsubvehnah8o06y6hh0qxlzgnaompd78kfj9e...
[2023-03-01T23:26:53.607Z] ^
[2023-03-01T23:26:53.607Z]
[2023-03-01T23:26:53.607Z] The above exception was the direct cause of the following exception:
[2023-03-01T23:26:53.607Z]
[2023-03-01T23:26:53.607Z] Traceback (most recent call last):
[2023-03-01T23:26:53.607Z] File "/app/api/run_task.py", line 160, in run
[2023-03-01T23:26:53.607Z] self.task_instance._run_raw_task()
[2023-03-01T23:26:53.607Z] File "/run/clehe8kvc0008ednwcxhe1xge/airflow/utils/session.py", line 75, in wrapper
[2023-03-01T23:26:53.607Z] return func(*args, session=session, **kwargs)
[2023-03-01T23:26:53.607Z] File "/run/clehe8kvc0008ednwcxhe1xge/airflow/models/taskinstance.py", line 1374, in _run_raw_task
[2023-03-01T23:26:53.607Z] self._execute_task_with_callbacks(context, test_mode)
[2023-03-01T23:26:53.607Z] File "/run/clehe8kvc0008ednwcxhe1xge/airflow/models/taskinstance.py", line 1520, in _execute_task_with_callbacks
[2023-03-01T23:26:53.607Z] result = self._execute_task(context, task_orig)
[2023-03-01T23:26:53.607Z] File "/run/clehe8kvc0008ednwcxhe1xge/airflow/models/taskinstance.py", line 1581, in _execute_task
[2023-03-01T23:26:53.607Z] result = execute_callable(context=context)
[2023-03-01T23:26:53.607Z] File "/run/clehe8kvc0008ednwcxhe1xge/astro/sql/operators/raw_sql.py", line 55, in execute
[2023-03-01T23:26:53.607Z] result = self.database_impl.run_sql(sql=self.sql, parameters=self.parameters, handler=self.handler)
[2023-03-01T23:26:53.607Z] File "/run/clehe8kvc0008ednwcxhe1xge/astro/databases/base.py", line 132, in run_sql
[2023-03-01T23:26:53.607Z] result = self.connection.execute(
[2023-03-01T23:26:53.607Z] File "/run/clehe8kvc0008ednwcxhe1xge/sqlalchemy/engine/base.py", line 1380, in execute
[2023-03-01T23:26:53.607Z] return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
[2023-03-01T23:26:53.607Z] File "/run/clehe8kvc0008ednwcxhe1xge/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
[2023-03-01T23:26:53.607Z] return connection._execute_clauseelement(
[2023-03-01T23:26:53.607Z] File "/run/clehe8kvc0008ednwcxhe1xge/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
[2023-03-01T23:26:53.607Z] ret = self._execute_context(
[2023-03-01T23:26:53.607Z] File "/run/clehe8kvc0008ednwcxhe1xge/sqlalchemy/engine/base.py", line 1943, in _execute_context
[2023-03-01T23:26:53.607Z] self._handle_dbapi_exception(
[2023-03-01T23:26:53.607Z] File "/run/clehe8kvc0008ednwcxhe1xge/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
[2023-03-01T23:26:53.607Z] util.raise_(
[2023-03-01T23:26:53.607Z] File "/run/clehe8kvc0008ednwcxhe1xge/sqlalchemy/util/compat.py", line 211, in raise_
[2023-03-01T23:26:53.607Z] raise exception
[2023-03-01T23:26:53.607Z] File "/run/clehe8kvc0008ednwcxhe1xge/sqlalchemy/engine/base.py", line 1900, in _execute_context
[2023-03-01T23:26:53.607Z] self.dialect.do_execute(
[2023-03-01T23:26:53.607Z] File "/run/clehe8kvc0008ednwcxhe1xge/sqlalchemy/engine/default.py", line 736, in do_execute
[2023-03-01T23:26:53.607Z] cursor.execute(statement, parameters)
[2023-03-01T23:26:53.607Z] File "/run/clehe8kvc0008ednwcxhe1xge/duckdb_engine/__init__.py", line 128, in execute
[2023-03-01T23:26:53.607Z] self.__c.execute(statement, parameters)
[2023-03-01T23:26:53.607Z] sqlalchemy.exc.ProgrammingError: (duckdb.CatalogException) Catalog Error: Table with name ivsubvehnah8o06y6hh0qxlzgnaompd78kfj9e3216lgoyxzldiy02h7we3qi4 does not exist!
[2023-03-01T23:26:53.607Z] Did you mean "pragma_database_list"?
[2023-03-01T23:26:53.607Z] LINE 2: SELECT * FROM ivsubvehnah8o06y6hh0qxlzgnaompd78kfj9e...
[2023-03-01T23:26:53.607Z] ^
[2023-03-01T23:26:53.607Z] [SQL:
[2023-03-01T23:26:53.607Z] SELECT * FROM ivsubvehnah8o06y6hh0qxlzgnaompd78kfj9e3216lgoyxzldiy02h7we3qi4
[2023-03-01T23:26:53.607Z] ]
[2023-03-01T23:26:53.607Z] (Background on this error at: https://sqlalche.me/e/14/f405)
[2023-03-01T23:26:53.607Z] ==================================================
[2023-03-01T23:26:53.607Z] Hint: the line number above corresponds to the dagfile if it's in an error in file "<string>". See the bottom drawer in the UI.
[2023-03-01T23:26:53.607Z] ==================================================
```

**Comment by pgzmnk** [comment]
@kaxil @phanikumv

**Comment by kaxil** [comment]
cc @tatiana @dimberman too to see if you'll have any thoughts/ideas on this -- whether it is possible or not

**Comment by tatiana** [comment]
@pgzmnk Please, let me know if I understood the request correctly: would you like to use in-memory Duck DB, hosted in the worker localhost, to exchange data across Airflow tasks?

**Comment by tatiana** [comment]
Thanks for the detailed description, @pgzmnk , I'm having a look now at the DAG and the code

**Comment by pgzmnk** [comment]
Thank you Tatiana. Let me know if you'd like to pair at any point.

**Comment by tatiana** [comment]
@pgzmnk this PR seems to resolve the issue: https://github.com/astronomer/astro-sdk/pull/1833

**Comment by pgzmnk** [comment]
This implementation successfully addresses the source [issue](Updated relevant issue https://app.zenhub.com/workspaces/cloud-ide-simplified-632a189ae801a8001d85bec0/issues/gh/astronomer/astro/10009).
