### ISSUE TITLE
Runtime - AstroSDK test failed on - 2023/11/21

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#2052]
Slack thread - https://astronomer.slack.com/archives/C059004990C/p1700672283297949

Stacktrace: 
```
[2023-11-22, 10:32:09 UTC] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/astro/sql/operators/load_file.py", line 131, in execute
    return self.load_data(input_file=self.input_file, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/astro/sql/operators/load_file.py", line 136, in load_data
    return self.load_data_to_table(input_file, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/astro/sql/operators/load_file.py", line 155, in load_data_to_table
    database.load_file_to_table(
  File "/usr/local/lib/python3.11/site-packages/astro/databases/base.py", line 513, in load_file_to_table
    self.create_table_if_needed(
  File "/usr/local/lib/python3.11/site-packages/astro/databases/base.py", line 430, in create_table_if_needed
    files = resolve_file_path_pattern(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/astro/files/base.py", line 284, in resolve_file_path_pattern
    raise FileNotFoundError(f"File(s) not found for path/pattern '{path_pattern}'")
FileNotFoundError: File(s) not found for path/pattern 'gdrive://test-google-drive-support/sample.csv'
```

**Comment by Lee-W** [comment]
@vatsrahul1001 As discussed on Monday and Tuesday, I believe we got it resolved. (due to permission issue) Is there anything we still want to track for this one?

**Comment by Lee-W** [comment]
As we've setup the permission, i'll move it to done
