### ISSUE TITLE
Fix or remove "tests/integration_test_dag.py"

### ISSUE THREAD

**Issue by kaxil** [astronomer/astro-sdk#415]
We have https://github.com/astronomer/astro-sdk/blob/main/tests/integration_test_dag.py file which is not being used in our test suite. I identified it when I passed it explicitly to pytest for https://github.com/astronomer/astro-sdk/pull/414/commits/42bcaefaece5ea1ce56b5766c501fe2d077fab26

If the tests in this file are already covered by other tests we have we should remove it.

The test is failing with the following error:

```

Location: US
Job ID: 269b39af-58b6-4ff0-afa5-ecaf6b672ef6

[SQL: ALTER TABLE astroflow_ci._tmp_ti2fyeniqgk86m8alla51zvx6oiqe2q6nsquwkkmu6vlg ADD CONSTRAINT airflow UNIQUE (list,sell)]
(Background on this error at: http://sqlalche.me/e/14/4xp6).
Traceback (most recent call last):
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 203, in _execute
    self._query_job.result()
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1499, in result
    do_get_result()
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1489, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Syntax error: Expected keyword CHECK or keyword FOREIGN or keyword PRIMARY but got keyword UNIQUE at [1:100]

Location: US
Job ID: 269b39af-58b6-4ff0-afa5-ecaf6b672ef6


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/google/cloud/bigquery/dbapi/_helpers.py", line 494, in with_closed_check
    return method(self, *args, **kwargs)
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 166, in execute
    self._execute(
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 205, in _execute
    raise exceptions.DatabaseError(exc)
google.cloud.bigquery.dbapi.exceptions.DatabaseError: 400 Syntax error: Expected keyword CHECK or keyword FOREIGN or keyword PRIMARY but got keyword UNIQUE at [1:100]

Location: US
Job ID: 269b39af-58b6-4ff0-afa5-ecaf6b672ef6


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/airflow/executors/debug_executor.py", line 79, in _run_task
    ti._run_raw_task(job_id=ti.job_id, **params)
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1452, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1599, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1660, in _execute_task
    result = execute_callable(context=context)
  File "/home/runner/work/astro-sdk/astro-sdk/src/astro/sql/operators/transform.py", line 80, in execute
    result = self.database_impl.run_sql(
  File "/home/runner/work/astro-sdk/astro-sdk/src/astro/databases/base.py", line 78, in run_sql
    result = self.connection.execute(sqlalchemy.text(sql_statement), parameters)
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1200, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1389, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1748, in _execute_context
    self._handle_dbapi_exception(
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1929, in _handle_dbapi_exception
    util.raise_(
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/google/cloud/bigquery/dbapi/_helpers.py", line 494, in with_closed_check
    return method(self, *args, **kwargs)
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 166, in execute
    self._execute(
  File "/home/runner/work/astro-sdk/astro-sdk/.nox/test-3-8-airflow-2-2-5/lib/python3.8/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 205, in _execute
    raise exceptions.DatabaseError(exc)
sqlalchemy.exc.DatabaseError: (google.cloud.bigquery.dbapi.exceptions.DatabaseError) 400 Syntax error: Expected keyword CHECK or keyword FOREIGN or keyword PRIMARY but got keyword UNIQUE at [1:100]

Location: US
Job ID: 269b39af-58b6-4ff0-afa5-ecaf6b672ef6

[SQL: ALTER TABLE astroflow_ci._tmp_ti2fyeniqgk86m8alla51zvx6oiqe2q6nsquwkkmu6vlg ADD CONSTRAINT airflow UNIQUE (list,sell)]
(Background on this error at: http://sqlalche.me/e/14/4xp6)
```

**Comment by sunank200** [comment]
this [line](https://github.com/astronomer/astro-sdk/blob/main/tests/integration_test_dag.py#L77) is adding a unique constraint in the Table. But in bigquery seems like there is no unique constraint: [reference](https://stackoverflow.com/questions/42938662/google-bigquery-there-are-no-primary-key-or-unique-constraints-how-do-you-preve)

The only constraint that BigQuery supports is `NOT NULL` one, and it is modeled by setting `REQUIRED` field mode on [table schema](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables)

Should i remove bigquery from this test?
