### ISSUE TITLE
Fix postgres benchmarking in K8s

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#830]
**Describe the bug**

When running the benchmark for all currently supported databases and datasets in Kubernetes (following #825), we have results for Snowflake. Still, the script fails when it reaches Postgres, for the 10 KB dataset:

```
+ python3 -W ignore /opt/app/python-sdk/tests/benchmark/run.py --dataset=ten_kb --database=postgres --revision 382c4a0 --chunk-size=1000000
Traceback (most recent call last):
  File "/opt/app/python-sdk/tests/benchmark/run.py", line 147, in <module>
    run_dag(
  File "/opt/app/python-sdk/tests/benchmark/run.py", line 67, in wrapper
    dag = func(*args, **kwargs)
  File "/opt/app/python-sdk/tests/benchmark/run.py", line 104, in run_dag
    dag.run(
  File "/usr/local/lib/python3.9/dist-packages/airflow/models/dag.py", line 2297, in run
    job.run()
  File "/usr/local/lib/python3.9/dist-packages/airflow/jobs/base_job.py", line 244, in run
    self._execute()
  File "/usr/local/lib/python3.9/dist-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/airflow/jobs/backfill_job.py", line 860, in _execute
    raise BackfillUnfinished(err, ti_status)
airflow.exceptions.BackfillUnfinished: Some task instances failed:
DAG ID                          Task ID    Run ID                                        Try number
------------------------------  ---------  ------------------------------------------  ------------
load_file_ten_kb_into_postgres  cleanup    backfill__2022-09-12T13:45:50.307817+00:00             1
load_file_ten_kb_into_postgres  load       backfill__2022-09-12T13:45:50.307817+00:00             1
```

We need to identify and fix any issues.

**Version**
* Astro: 1.0 (branch #825)

**To Reproduce**
If #825 was not merged yet, checkout the branch: `issue-798` and run:
```
make container
make run_job
```

**Acceptance criteria**
* [ ] We can run the benchmark script on Kubernetes for Postgres
* [ ] Update the results for Postgres in the document which summarises them

**Comment by pankajastro** [comment]
looks duplicate https://github.com/astronomer/astro-sdk/issues/914. Please re-open if require
